src/test/html/AccountSettingsOpen.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsOpenIT.java

Open and close Account Settings

Add AccountSettingsOpen

---

src/test/html/AccountSettingsOpen.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsOpenIT.java

Waited for "Account Settings" header text on the account settings modal.

Fix AccountSettingsOpen

---

src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

Fixes for security tests. Wait for password field, use Disable Animations on second open of login page

Lm patch 1

---

src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

Wait for Save not present, instead of next element present

Lm patch sec

---

src/test/html/AccountSettingsFullName.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java

Lm patch fullname

---

src/test/html/AccountSettingsFullName.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java

FullName fix: Fewer waitForElements and remove failing logout.

Lindalumitchell patch 1

---

src/test/html/AccountSettingsNickname.html

Rewrite with new IDs and to complete release spreadsheet tests

Update nickname test with new IDs

---

src/test/html/AccountSettingsFullName.html

Rewrite with new IDs and to complete release spreadsheet tests

Update FullName with new IDs

---

src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

Updated AccountSettingsSecurity with new IDs and filling in the rest of the tests from the release spreadsheet for that section.

Lm security

---

src/test/html/AccountSettingsUsername.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsUsernameIT.java

Fix clearing of username field

---

src/test/html/AccountSettingsFullName.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java

After export to java, replaced each line that used KEY_BACKSPACE in IDE with two lines in the java code:
`driver.findElement(By.id("firstName")).sendKeys("h");`
`driver.findElement(By.id("firstName")).sendKeys("\u0008");`

FullName updated IDs and workaround for clearing fields

---

src/test/html/AccountSettingsNotifications.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java

Java is having issues, possibly with the radio buttons, or with some elements being off screen. Adding test here so others can investigate as well, if needed.

Adding Notifications test

---

src/test/html/AccountSettingsFullName.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java

Comments in file describe four manual edits to make in java file after export from html (to make clearing fields work).

Updated FullName java to clear fields

---

src/test/html/AccountSettingsDisplay.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsDisplayIT.java

Java is still failing, but adding to repo for further investigation.

Adding Display test

---

src/test/html/LogInLogOut.html
src/test/java/com/mattermost/selenium/tests/LogInLogOutIT.java

Can be used as a template for new tests.

Adding test steps for logging in and logging out

---

src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

And adding more wait commands.

Using test2 user in Security test

---

src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

Despite several commands to wait for elements, test still not finding fields in time to enter data. Trying a couple more Sleep comment pauses.

Security test: Adding two more Sleeps

---

src/test/html/AccountSettingsDisplay.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsDisplayIT.java

Also changed some assertValue to waitForValue or waitForChecked/NotChecked.

Updating Display test to replace object_Object IDs

---

src/test/html/AccountSettingsNotifications.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java

And added some sleeps and removed Email Notification section (disabled by default).

Updating Notifications with new IDs

---

src/test/html/AccountSettingsDisplay.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsDisplayIT.java

Removed assert, waitFor, verify for value = off or on, and for checked or notchecked. Added in some waitForElementPresents instead.

Display test: Removed value verifications

---

src/test/html/AccountSettingsNotifications.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java

Removed assert, waitFor, verify for value off or on, and for checked or notchecked.

Notifications test: Removed value verifications

---

src/test/html/AccountSettingsFullName.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java

And remove a couple wait commands.

FullName: Add field clearing back to test

---

src/test/html/AccountSettingsFullName.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java

Clearing fields is still failing, even after adding another .clear() after the sendKeys character backspace command.

FullName: Taking field clearing back out

---

src/test/html/Integrations.html

IDE only for now (no Java version)

Adding Integrations.html

---

src/test/html/TeamSettings.html

Adding TeamSettings.html

---

src/test/html/SystemConsoleGeneralPolicy.html

Changes:
-Fixed missing "id="
-Added few waitForElementPresent before verifyElementNotPresent
Addition:
Added Policy -> Enable Public Channel Creation Setting

Add enable public channel creation test to SystemConsoleGeneralPolicy

---

src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java

At-here is now included in the list of words triggering mentions by default (PR 6372)

Add at-here to default mention words in Notifications test

---

src/test/html/MessagingBasics.html

IDE only for now; not working on build.

Add test MessagingBasics.html

---

src/test/html/TeamSettingsNameDesc.html
src/test/java/com/mattermost/selenium/tests/TeamSettingsNameDescIT.java

Remove additional extra verification

---

src/test/html/AccountSettingsDisplay.html
src/test/html/ChannelSettingsPubHeader.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsDisplayIT.java
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

In Channel Settings: Updated CSS on element in edit header modal.
In Display: Changed to verify ES string that will always be on-screen despite other activity in-channel.

ChannelHeader and Display locator updates

---

src/test/html/ide-only/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/ChannelName.html
src/test/html/ide-only/ChannelNotificationsUI.html
src/test/html/ide-only/ChannelSettingsPriHeader.html
src/test/html/ide-only/ChannelSettingsPurpose.html
src/test/html/ide-only/OBTeamNameURL.html
src/test/html/ide-only/SysConsConfiguration.html
src/test/html/ide-only/SysConsLocalization.html
src/test/html/ide-only/SysConsReporting.html
src/test/html/ide-only/SysConsUserMgmt.html
src/test/html/ide-only/SysConsUserPwdDeact.html
src/test/html/ide-only/SysConsUsersTeamsCreation.html
src/test/html/ide-only/SysConsUsersTeamsMaxes.html

AccountSettingsDisplayLanguage.html
ChannelName.html
ChannelSettingsPriHeader.html
ChannelPurpose.html
ChannelNotificationsUI.html
OBTeamNameURL.html
SysConsConfiguration.html
SysConsLocalization.html
SysConsReporting.html
SysConsUserMgmt.html
SysConsUserPwdDeact.html
SysConsUsersTeamsCreation.html
SysConsUsersTeamsMaxes.html

Adding 13 more HTML tests

---

setup-for-run.sh

While investigating regular daily build failure (after adding a bunch of new HTML files)

Locking to 4.2.0 release build

---

src/test/html/AccountSettingsDisplay.html
src/test/html/AccountSettingsFullName.html
src/test/html/AccountSettingsNotifications.html
src/test/html/AccountSettingsSecurity.html
src/test/html/AccountSettingsUsername.html
src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsDisplayIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsUsernameIT.java
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

Mostly within Account Settings modal, plus some Channel Settings and Search.

Updating more locators with IDs

---

src/test/html/TeamSettingsNameDesc.html
src/test/java/com/mattermost/selenium/tests/TeamSettingsNameDescIT.java

Wait command is not working; it finds the button but can't click it. Adding a sleep command makes it work locally.

Team Name - Add sleep to find button clickable

---

src/test/html/ChannelSettingsPubHeader.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

In public channel creation form

Update create private channel from link to button

---

src/test/html/ChannelSettingsPubHeader.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

Found these improvements for the test while testing if channel edit was fixed (https://github.com/mattermost/mattermost-webapp/pull/367)

Channel header: IDs or css locators instead of xpath

---

src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html

ChannelJoinLeave.html
ChannelManageMembers.html
ChannelName.html
ChannelNotificationsUI.html
ChannelSettingsPriHeader.html
ChannelPurpose.html

Adding and organizing Channel IDE test files

---

src/test/html/ide-only/Auth/AuthAD_LDAP.html
src/test/html/ide-only/DM/DM.html
src/test/html/ide-only/EmailVerify/EmailVerifyMan.html
src/test/html/ide-only/Files/FilesAttachmentsMan.html
src/test/html/ide-only/Integrations/IntegrationsSlashCmds.html
src/test/html/ide-only/Integrations/IntegrationsSlashRemove.html

AuthAD_LDAP.html
DM.html
EmailVerifyMan.html
FilesAttachmentsMan.html
IntegrationsSlashCommands.html
IntegrationsSlashRemove.html

Adding and organizing several IDE tests

---

src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/Messaging/MessagingEdit.html
src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Messaging/MessagingFlags.html
src/test/html/ide-only/Messaging/MessagingMan.html
src/test/html/ide-only/Messaging/MessagingPin.html

MessagingBasics.html
MessagingEdit.html
MessagingEmojiCustom.html
MessagingFlags.html
MessagingMan.html
MessagingPin.html

Create Messaging folder and add six IDE test files

---

src/test/html/ide-only/Auth/AuthEmailPwd.html
src/test/html/ide-only/Notifications/NotificationsMan.html
src/test/html/ide-only/Notifications/NotificationsPunctuation.html
src/test/html/ide-only/Notifications/NotificationsUI.html
src/test/html/ide-only/OB/OBTeamNameURL.html
src/test/html/ide-only/Search/Search.html
src/test/html/ide-only/Search/SearchHashtags.html

AuthEmailPwd.html
NotificationsUI.html
NotificationsMan.html
NotificationsPunctuation.html
OBTeamNameURL.html
Search.html
SearchHashtags.html

Adding more Se IDE test files

---

src/test/html/ide-only/SystemConsole/SysConsAnnouncement.html
src/test/html/ide-only/SystemConsole/SysConsComplianceLogging.html
src/test/html/ide-only/SystemConsole/SysConsConfiguration.html
src/test/html/ide-only/SystemConsole/SysConsDataRetention.html
src/test/html/ide-only/SystemConsole/SysConsExport.html
src/test/html/ide-only/SystemConsole/SysConsGeneralPolicy.html
src/test/html/ide-only/SystemConsole/SysConsLocalization.html
src/test/html/ide-only/SystemConsole/SysConsPassword.html
src/test/html/ide-only/SystemConsole/SysConsPlugins.html
src/test/html/ide-only/SystemConsole/SysConsPolicy1Setup.html
src/test/html/ide-only/SystemConsole/SysConsPolicy2Invites.html
src/test/html/ide-only/SystemConsole/SysConsPolicy3Channels.html
src/test/html/ide-only/SystemConsole/SysConsReporting.html
src/test/html/ide-only/SystemConsole/SysConsRestrictAcctDomain.html
src/test/html/ide-only/SystemConsole/SysConsTeammateName.html
src/test/html/ide-only/SystemConsole/SysConsUserMgmt.html
src/test/html/ide-only/SystemConsole/SysConsUserPwdDeact.html
src/test/html/ide-only/SystemConsole/SysConsUsersTeamsCreation.html
src/test/html/ide-only/SystemConsole/SysConsUsersTeamsDM.html
src/test/html/ide-only/SystemConsole/SysConsUsersTeamsMaxes.html

SysConsAnnouncement.html
SysConsComplianceLogging.html
SysConsConfiguration.html
SysConsDataRetention.html
SysConsExport.html
SysConsGeneralPolicy
SysConsLocalization.html
SysConsPassword.html
SysConsPlugins.html
SysConsPolicy1Setup.html
SysConsPolicy2Invites.html
SysConsPolicy3Channels.html
SysConsReporting.html
SysConsRestrictAcctDomain.html
SysConsTeammateName.html
SysConsUserMgmt.html
SysConsUserPwdDeact.html
SysConsUsersTeamsCreation.html
SysConsUsersTeamsDM.html
SysConsUsersTeamsMaxes.html

Adding and organizing 20 System Console IDE test files

---

src/test/html/ide-only/Smoke/SmokeTestRC.html
src/test/html/ide-only/Team/TeamMulti.html
src/test/html/ide-only/Team/TeamSettings.html
src/test/html/ide-only/Team/TeamSettingsEnableJoin.html

TeamSettingsEnableJoin.html
TeamSettings.html
TeamSettingsEnableJoin.html
SmokeTestRC.HTML

Adding Team and smoke test IDE test files

---

src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/SearchIT.java

Reverts mattermost/mattermost-selenium#196

Revert "Use backspaces instead of type to clear search field"

---

src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/SearchIT.java

When posting initial /test command.

Separating key Enter from message text

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Auth/AuthAD_LDAP.html
src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

Including removing the APIv3 deprecation banner steps from the
ChannelSettingsPubHeader test in the build.

Updates to Account Settings and Channel tests during release testing

---

src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/Messaging/MessagingEdit.html
src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Messaging/MessagingMan.html

Updates to Messaging tests during release testing

---

src/test/html/ide-only/Messaging/MessagingPin.html
src/test/html/ide-only/Notifications/Notifications.html
src/test/html/ide-only/Notifications/NotificationsMan.html
src/test/html/ide-only/Notifications/NotificationsPunctuation.html
src/test/html/ide-only/Notifications/NotificationsUI.html
src/test/html/ide-only/SystemConsole/SysConsComplianceLogging.html
src/test/html/ide-only/SystemConsole/SysConsConfiguration.html
src/test/html/ide-only/SystemConsole/SysConsPassword.html
src/test/html/ide-only/SystemConsole/SysConsPolicy1Setup-compare.html
src/test/html/ide-only/SystemConsole/SysConsPolicy2Invites.html
src/test/html/ide-only/SystemConsole/SysConsPolicy3Channel-compare.html
src/test/html/ide-only/SystemConsole/SysConsTeammateName.html
src/test/html/ide-only/SystemConsole/SysConsUsersDeactivate.html
src/test/html/ide-only/SystemConsole/SysConsUsersTeamsCreation.html
src/test/html/ide-only/SystemConsole/SysConsUsersTeamsDM.html
src/test/html/ide-only/SystemConsole/SysConsUsersTeamsMaxes.html
src/test/html/ide-only/Team/TeamMulti.html
src/test/html/ide-only/Team/TeamSettings.html

Plus other tweaks, found during release testing.

Many test updates, mostly removing -textarea

---

src/test/html/ide-only/Smoke/ST.html
src/test/html/ide-only/SystemConsole/SysConsComplianceLogging.html
src/test/html/ide-only/_snippets/StorePostID.html

Also adding a new Snippets folder for useful sequences.

Updates to smoke test and a system console test

---

src/test/html/AccountSettingsNotifications.html
src/test/html/ide-only/SystemConsole/SysConsPolicy3Channel-compare.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java

Also a tweak to IDE-only Policy3Channel.

Updated helper text in push notifications

---

src/test/html/AccountSettingsDisplay.html
src/test/html/AccountSettingsFullName.html
src/test/html/AccountSettingsNickname.html
src/test/html/AccountSettingsNotifications.html
src/test/html/AccountSettingsPosition.html
src/test/html/AccountSettingsSecurity.html
src/test/html/AccountSettingsUsername.html
src/test/html/Search.html
src/test/html/TeamSettingsNameDesc.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsDisplayIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsFullNameIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsNicknameIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsPositionIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsUsernameIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java
src/test/java/com/mattermost/selenium/tests/TeamSettingsNameDescIT.java

PR that added IDs:
https://github.com/mattermost/mattermost-webapp/pull/951

Updating tests in nightly build with new settings IDs

---

src/test/html/AccountSettingsNotifications.html
src/test/html/AccountSettingsPosition.html
src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsPositionIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

Missed an ID, also tried adding a new verify for updated timestamp on
password change.

Further tweaks after updating IDs

---

src/test/html/AccountSettingsPosition.html
src/test/html/AccountSettingsSecurity.html

- Security test: Trying to verify updated password timestamp a
different way (this was a new verification added recently)
- Position test: Going back to old way of clearing field (seemed more
brittle the old way, but actually passes much more reliably)

Update AccountSettings tests

---

src/test/html/AccountSettingsPosition.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsPositionIT.java

Added back in an extra type / clear after.

Position test: Back to the old way of clearing a field

---

src/test/html/AccountSettingsSecurity.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsSecurityIT.java

Changing from verifying field ID to button ID

Security test: Another try to preserve last verify of login screen

---

src/test/html/Search.html
src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html
src/test/html/ide-only/Channel/ChannelSettingsSuite

CSS locators changed in Search test (failed in build).
Also added a new Channel test for converting public to private, and
updated the rest of the Channel tests (and suite).

Update and add Channel tests, update Search

---

src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/SearchIT.java

And wildcard after channel name to accommodate mention badge

Adding confirmation of at-channel

---

setup-for-run.sh

Add delay of 60s before starting the server

Add delay of 60s before starting the server

---

setup-for-run.sh

Increase delay to 120s before starting the server
@lindalumitchell I'll go ahead merge this again.

Increase delay to 120s before starting the server

---

setup-for-run.sh

Set version to mattermost-5.0.0-rc2
@lindalumitchell I'll go ahead and merge this.

Set version to mattermost-5.0.0-rc2

---

setup-for-run.sh

Reverts mattermost/mattermost-selenium#278
- Will just try to revert to isolate this from what causing the recent failure in UI automation

Revert "replace the platform binary to mattermost"

---

src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html
src/test/html/ide-only/Notifications/NotifyMentions.html

Account Settings, Channel Settings, Notifications tests (so far)

Updates during release testing v5.0

---

src/test/html/ChannelSettingsPubHeader.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

Locator changed for element in header popover.

Update Channel Header test

---

src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/Channel/ChannelManageMembers.html

Changing `delete` to `archive` for channels.

Updates to Channel tests

---

src/test/html/ide-only/Messaging/MessagingBasics.html

Added test for non-letter character following period in URL

Updating MessagingBasics.html

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html

- Advanced permissions Console test
- Advanced permissions Combination tests

Added Tests for Adv Permissions

---

src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/Messaging/MessagingMan2.html
src/test/html/ide-only/Search/Search.html
src/test/html/ide-only/SystemConsole/scUsersTeamsMaxes.html

Also added new test "MessagingMan2"

Updates to Se tests from v5.2 release

---

src/test/html/ide-only/Experimental/channelSidebar.html

Note: One item will continue to fail until https://mattermost.atlassian.net/browse/MM-11843 is fixed.

Finish channelSidebar.html test

---

setup-for-run.sh

Reverts mattermost/mattermost-selenium#326

Revert "Locking to 5.4.0-rc2"

---

src/test/html/ide-only/DM/DM.html
src/test/html/ide-only/Files/FilesAttachmentsMan.html
src/test/html/ide-only/Integrations/IntegrationsSlashCmds.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html

- Updated some locators to accommodate small CSS changes 
- Added a few comments to clarify some areas of tests,

Minor maintenance changes for 5.4

---

src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/Messaging/MessagingMan.html
src/test/html/ide-only/Notifications/NotifyMentions.html

A couple of small edits to tests

Updates from 5.4 testing

---

src/test/html/ide-only/Auth/AuthAD_LDAP.html
src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/EmailVerify/EmailVerifyMan.html
src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/Smoke/ST.html
src/test/html/ide-only/SystemConsole/scAnnouncement.html
src/test/html/ide-only/SystemConsole/scBranding.html
src/test/html/ide-only/SystemConsole/scCustomLinks.html
src/test/html/ide-only/SystemConsole/scNotificationSettings.html
src/test/html/ide-only/SystemConsole/scNotificationsMan.html
src/test/html/ide-only/SystemConsole/scPlugins.html
src/test/html/ide-only/SystemConsole/scPrivacy.html
src/test/html/ide-only/SystemConsole/scRestrictAcctDomain.html
src/test/html/ide-only/SystemConsole/scSecSignup.html
src/test/html/ide-only/SystemConsole/scSecurity.html
src/test/html/ide-only/SystemConsole/scSubpath.html
src/test/html/ide-only/SystemConsole/scSuite
src/test/html/ide-only/SystemConsole/scTeammateName.html
src/test/html/ide-only/SystemConsole/scUsersTeamsCreation.html
src/test/html/ide-only/SystemConsole/scUsersTeamsDM.html
src/test/html/ide-only/SystemConsole/scUsersTeamsMaxes.html
src/test/html/ide-only/Team/TeamSettings.html

Auth, Channel, Email, Messaging, System Console, Smoke test, Team tests.
(Looks like my last PR didn't include any of these changes.)

Updates from v5.4 release testing

---

src/test/html/ide-only/Integrations/IntegrationsSlashCmds.html
src/test/html/ide-only/KeyShortcuts/KeyShortcutsUp.html
src/test/html/ide-only/Team/TeamSettings.html

Fixed a few random things found in tests during 5.5 release testing.

Couple of updates to tests from 5.5 release testing

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/ide-only/SystemConsole/scPlugins.html

- Channel creation modal (public / private options)
- Plugins Configuration page folded into Management page

Test updates for UI changes in v5.6

---

src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

Adding the public/private radio buttons from sidebar reorg work.

Update channel creation UI

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

UI elements changed, including:
- Channel creation modal (changed for everyone as a result of sidebar reorganization)
- Profile popover as a result of new role badges
- Some text changes

Updates to fix build tests Search, ChannelSettingsPubHeader

---

src/test/html/ChannelSettingsPubHeader.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java

ID still appears to be present for Channel View Info, and the test can find it successfully in IDE, but Java fails to find it by ID. Trying CSS instead.

Trying a different identifier for Channel View Info

---

src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelJoinLeaveMsgs.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/SystemConsole/scExport.html

Maintenance work on some Se tests

Standard Maintenance

---

src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/Channel/ChannelJoinLeaveMsgs.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html

5.6 Maintenance

---

src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Smoke/ST.html

(Inadvertently put both commits on this PR)
- Updates to ST.html during v5.6 release testing
- Added test for deactivating own account to AccountSettingsMan.html (plus a few other updates, during v5.7 release testing)

Update smoke test and AccountSettingsMan.html

---

src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

- Updated login to always use 'passwd' as password instead of user supplied value
- Corrected errors in some comments
- Added Create Private Channel
- Added Promote user to System Admin
- Added Remove user from team
- Added Create team
- Added Add user to team

Update userextension-rollup.js to support more permissions cases

---

setup-for-run.sh

Add I had missed a replace in 1st attempt to update the file.

Locking to RC5

---

src/test/html/AccountSettingsNotifications.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java

This text was removed in https://mattermost.atlassian.net/browse/MM-11936. Removing it from the verification in this test.

Removing "for 5 seconds" from Notifications test

---

src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html

- Updates to permissions tests (including adding Permissions-Full)
- Added edge case to custom emoji test
**Note**: I did not commit these along with the rest of my maintenance as they use rollup commands and other team members did not yet have the JS extension.

Se IDE test updates for 5.7

---

setup-for-run.sh

fixes: https://mattermost.atlassian.net/browse/MM-13803

change the order to start the server

---

setup-for-run.sh

add missing sys admin flag when creating the admin user

fix missing sysadmin flag

---

src/test/html/ide-only/Auth/AuthAD_LDAP.html
src/test/html/ide-only/Auth/AuthSAML.html

- LDAP: Messaging change
- SAML: Update special characters

Update Auth tests

---

src/test/html/ide-only/SystemConsole/scAuthEmailUsername.html

Update to AuthEmail test

---

src/test/html/ide-only/SystemConsole/scComplianceLogging.html
src/test/html/ide-only/SystemConsole/scCustomLinks.html
src/test/html/ide-only/SystemConsole/scLocalization.html
src/test/html/ide-only/SystemConsole/scNotificationsMan.html
src/test/html/ide-only/SystemConsole/scPlugins.html
src/test/html/ide-only/SystemConsole/scSubpath.html
src/test/html/ide-only/SystemConsole/scUsersDeactivate.html
src/test/html/ide-only/SystemConsole/scUsersEmail.html
src/test/html/ide-only/SystemConsole/scUsersMgmt.html
src/test/html/ide-only/SystemConsole/scUsersPassword.html
src/test/html/ide-only/SystemConsole/scUsersTeamsDM.html
src/test/html/ide-only/SystemConsole/scUsersTeamsMaxes.html

- ComplianceLogging: Better verification elements in job table
- CustomLinks: Correct browser title verification
- Localization: Locator changed to ID for available locales
- NotificationsMan: Button ID changed, update test text for notification
- Plugins: JIRA to Jira, button ID changed
- Subpath: Remove Town Square verification (no longer accurate), add a
couple comments
- UsersDeactivate: Button ID changed, make input location less brittle,
make user count text verification less brittle
- UsersEmail: Update helper text on invalid credentials
- UsersMgmt: Button ID changed, make user count text verification less
brittle
- UsersPassword: Verify on text box instead of Town Square, make user
count text verification less brittle
- UsersTeamsDM: Button ID changed, make input location less …

Updates to System Console tests

---

src/test/html/ide-only/Messaging/MessagingBasics.html

Sysadmin should be shown proper "message not found" page when trying to follow a DM permalink that belongs to other users.

Added test for Sysadmin see's proper error message when following permalink for DM between 2 other users

---

src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/AccountSettings/AccountSettingsMan.html

DisplayLanguage: 
- One translation string changed in Polish
ASMan:
- Added profile pic removal then adding new immediately
- Locator for image preview changed
- ID for join/leave msg setting changed
- Updated join/leave behavior
- Updated markdown preview locator
- Removed duplicate test rows at end

Update Account Settings tests during v5.8 testing

---

src/test/html/ide-only/Auth/AuthEmailPwd.html
src/test/html/ide-only/Messaging/MessagingPin.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/SystemConsole/scUsersMgmt.html
src/test/html/ide-only/Team/TeamMulti.html
src/test/html/ide-only/Team/TeamSettings.html

- Added 1 of 2 scenarios for Team Override Scheme to Permissions-Full
- Standard maintenance on permissions tests
- Added test to scUserMgmt including new status filter
- Added cases to TeamSettings to cover user joining a team when email domain restriction will not allow it

5.8 Selenuim work

---

src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html

PR from new Se branch for 5.9 work.
- Added Jumbo emojis tests and other emoji test
- Added test to ensure user cannot abuse edit permissions to delete a post

Comit from new SE branch for 5.9 work

---

setup-for-run.sh

Bumping Version to 5.9rc1

---

src/test/html/ide-only/SystemConsole/scConfiguration.html
src/test/resources/RepositoryMap.xml

- Update chrome and firefox drivers, and removed unused ones
- Update other remaining URL to point to new URL
Note that this will not generate a total passing tests but at least the Selenium will run (connecting Selenium and server instance).  Remaining failing test are due to some element IDs that cannot be found.  Will deal with those separately.
I'll go ahead and merge this to see how it runs on server.

MM-14732 Update chrome and firefox drivers, and removed unused ones

---

src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Messaging/MessagingMan.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Search/Search.html
src/test/html/ide-only/SystemConsole/scNotificationsMan.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

5.9 Selenium Maintenance

---

src/test/java/com/mattermost/selenium/config/DriverType.java

Run chrome and firefox drivers in headless mode

[MM-14732] Run chrome and firefox drivers in headless mode

---

setup-for-run.sh

Updating server to Bumping to 5.10.0-rc3

Bumping to 5.10.0-rc3

---

src/test/html/AccountSettingsOpen.html
src/test/html/AccountSettingsPosition.html
src/test/html/ChannelSettingsPubHeader.html
src/test/html/LogInLogOut.html
src/test/html/Search.html
src/test/html/TeamSettingsNameDesc.html
src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/Auth/AuthAD_LDAP.html
src/test/html/ide-only/Auth/AuthSAML.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/SystemConsole/scAnnouncement.html
src/test/html/ide-only/SystemConsole/scBranding.html
src/test/html/ide-only/SystemConsole/scNotificationSettings.html
src/test/html/ide-only/SystemConsole/scNotificationsMan.html
src/test/html/ide-only/SystemConsole/scPassword.html
src/test/html/ide-only/SystemConsole/scSecSignup.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsOpenIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsPositionIT.java
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/LogInLogOutIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java
src/test/java/com/mattermost/selenium/tests/TeamSettingsNameDescIT.java

Many tests updated during v5.10 (build and IDE-only), including these changes:
- Logout button changed from ID to CSS
- Drop-down options changed from ID to CSS including Channel and Team
Settings, main menu items (menu from main page and from System
Console), User role settings,
- Polish from Alpha to Beta
- Tests added for message box placeholder text
- Test added for custom branding turned on but no image uploaded
- Test server names updated after migration (postgres.test, e.g)

Updates during v5.10 testing

---

src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

The following less commonly used rollup commands also required maintenance. 
- Open Channel from sidebar
- Add user to channel
- Promote user to channel Admin
- Remove user from channel
- Remove user from team
- Create Team
- Add user to team

Additional locator fixes for rollup commands

---

setup-for-run.sh

Locking to 5.10.0-rc6

---

setup-for-run.sh

Fixed Missed RC reference in package name

Fixed Missed RC reference in package name

---

src/test/html/AccountSettingsPosition.html
src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/html/TeamSettingsNameDesc.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsPositionIT.java
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java
src/test/java/com/mattermost/selenium/tests/TeamSettingsNameDescIT.java

- Search test: Adding step to open flagged RHS to ensure search box is visible
- Other three tests: Removing superfluous dot in CSS button style (after `none`)

Fixes for build failures v5.11

---

src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/SystemConsole/scBranding.html
src/test/html/ide-only/SystemConsole/scUsersTeamsCreation.html
src/test/html/ide-only/SystemConsole/scUsersTeamsMaxes.html
src/test/html/ide-only/Team/TeamSettingsEnableJoin.html

Please check the steps I added to scBranding.html as there was a whole chunk missing and I just want to be sure everything's ok. The test ran and passed.

Updates to Se tests for 5.11 testing

---

src/test/html/ide-only/Auth/AuthGitLab.html
src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/DM/DM.html
src/test/html/ide-only/Messaging/MessagingEdit.html
src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Notifications/NotifyMan.html
src/test/html/ide-only/Notifications/NotifyMentions.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/SystemConsole/scUsersMgmt.html
src/test/html/ide-only/SystemConsole/scUsersPassword.html
src/test/html/ide-only/Team/TeamMulti.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

5.11 Maintenance Work

---

src/test/html/ide-only/Auth/AuthAD_LDAP.html
src/test/html/ide-only/Auth/AuthGitLab.html
src/test/html/ide-only/Auth/AuthSAML.html
src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/Integrations/IntegrationsSlashCmds.html
src/test/html/ide-only/Messaging/MessagingPin.html
src/test/html/ide-only/SystemConsole/scCustomLinks.html
src/test/html/ide-only/SystemConsole/scNotificationsMan.html
src/test/html/ide-only/SystemConsole/scPlugins.html
src/test/html/ide-only/SystemConsole/scSubpath.html
src/test/html/ide-only/SystemConsole/scTermsofService.html

Mostly straggler server and menu option updates

Test updates v5.11

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

... to try to bypass failures with pages not fully rendering.

Update locators and add one refresh

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

Channel header and Search tests

Updating locators that changed

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

Maintenance on permissions and Rollups for 5.12
@lindalu Note that the updates to the user extension file will be needed to make the final smoke test run smoothly.

Maintenance on permissions and Rollups for 5.12

---

src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/AccountSettings/AccountSettingsEmail.html
src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html
src/test/html/ide-only/Notifications/NotifyMan.html

PR includes a few small updates to tests run during 5.12 release.

A few small updates to tests from 5.12 release

---

src/test/html/ide-only/Channel/ChannelJoinLeave.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelName.html
src/test/html/ide-only/Channel/ChannelNotificationsUI.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/Channel/ChannelSettingsPurpose.html
src/test/html/ide-only/DM/DM.html
src/test/html/ide-only/Experimental/channelSidebar.html
src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Plugins/pluginsSettings.html

5.13 Maintenance Work

---

src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

Fixed Rollups that grab Hamburger menu. span has been changed to a button causing these to fail

Fixed Rollups that grab Hamburger menu

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Plugins/pluginsSettings.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

- Maintenance on Permissions and plugin test
- Added tests to _Permissions-Full_ to check Public, Private and Default channel types for any extra divider bar in channel menu. (This was done with roll up extension.)

5.14 maintenance + Check for extra divider bars in channel menu

---

setup-for-run.sh
src/test/html/ide-only/Auth/auth06-LDAPGroups.html
src/test/html/ide-only/Integrations/IntegrationsSlashCmds.html
src/test/html/ide-only/Smoke/ST.html

LDAP Groups, Slash Commands, Smoke Test

Updates for v5.15 testing

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

Udated Rollup for Add to Team UI

Update userextension-rollup.js  for Add to Team UI

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Plugins/pluginsSettings.html

5.17 Maintenance

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

Updated various locators, removed some superfluous steps.

Fix failing tests for Channel Header and Search

---

src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

Corrected some format settings.

Re-export files to .java

---

setup-for-run.sh
src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

Switching the server from RC1 to release branch.
Also updating Search and Channel Header tests with changes to locators and search icon instead of search box.

Fix test failures, server from rc1 to release branch

---

setup-for-run.sh

Locking to v5.18-rc3

---

setup-for-run.sh

Lock to v5.18-rc4

---

src/test/html/ChannelSettingsPubHeader.html
src/test/html/Search.html
src/test/java/com/mattermost/selenium/tests/ChannelSettingsPubHeaderIT.java
src/test/java/com/mattermost/selenium/tests/SearchIT.java

In Channel header (public) and Search tests. They both work fine locally, with the several approaches I've tried, but then fail in the build. Trying one more approach.

Update failing locators

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Plugins/pluginsSettings.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

Maintenance Work for 5.20
Maintenance work to permissions tests. Significant refactoring needed for roll-ups to accomidate for CSS changes.

Maintenance Work for 5.20

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Plugins/pluginsSettings.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

- Minor maintenance. They all look like changes that were skiped over during the 5.20 run.
- Fixed rollup to get post by text using much simpler infinite look-down xpath so I no longer need to manually select some posts during permissions testing. (previous version was too brittle to maintain)

5.21 Maintenance

---

src/test/resources/RepositoryMap.xml

Update chromedriver to 79

---

pom.xml
src/test/java/com/mattermost/selenium/config/DriverFactory.java
src/test/java/com/mattermost/selenium/config/DriverType.java

Removed unsupported drivers due to upgraded Selenium versions.
Note: We're only testing against Chrome browser.

Removed unsupported drivers

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Permissions/scPermissionSchemes.html
src/test/html/ide-only/Plugins/pluginsSettings.html

- Standard maintence.
- Some outstnding changes where needed to accomidate which plugins exist in fresh state.
<!-- Thank you for contributing a pull request! Here are a few tips to help you:
1. If this is your first contribution, make sure you've read the Contribution Checklist https://developers.mattermost.com/contribute/getting-started/contribution-checklist/
2. Read our blog post about "Submitting Great PRs" https://developers.mattermost.com/blog/2019-01-24-submitting-great-prs
3. Take a look at other repository specific documentation at https://developers.mattermost.com/contribute

5.22 Maintenance

---

setup-for-run.sh
src/test/html/ide-only/AccountSettings/AccountSettingsDisplayLanguage.html
src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/Auth/auth01-Signup.html
src/test/html/ide-only/Auth/auth06-LDAPGroups.html
src/test/html/ide-only/Auth/auth06.5-LDAPGroupSync.html
src/test/html/ide-only/Auth/auth06.75-LDAPSyncRoles.html
src/test/html/ide-only/Auth/auth07-SAML.html
src/test/html/ide-only/Auth/auth08-GitLab.html
src/test/html/ide-only/Channel/ChannelConvertPubToPrivate.html
src/test/html/ide-only/Channel/ChannelManageMembers.html
src/test/html/ide-only/Channel/ChannelSettingsPriHeader.html
src/test/html/ide-only/DM/DM.html
src/test/html/ide-only/EmailVerify/EmailVerifyMan.html
src/test/html/ide-only/Files/FilesAttachmentsMan.html
src/test/html/ide-only/Integrations/IntegrationsSlashCmds.html
src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/Messaging/MessagingEmojiCustomMan.html
src/test/html/ide-only/Messaging/MessagingMan.html
src/test/html/ide-only/Messaging/MessagingPin.html
src/test/html/ide-only/SystemConsole/sc05-UsersDeactivate.html
src/test/html/ide-only/SystemConsole/sc06.5-EnvSubpath.html
src/test/html/ide-only/SystemConsole/sc10-Localization.html
src/test/html/ide-only/Team/TeamMulti.html

Test maintenance from v5.23 and putting server on v5.24.

Updates from v5.23 testing

---

src/test/html/AccountSettingsNotifications.html
src/test/html/AccountSettingsUsername.html
src/test/html/ide-only/AccountSettings/AccountSettingsMan.html
src/test/html/ide-only/SystemConsole/sc03-UsersEmail.html
src/test/java/com/mattermost/selenium/tests/AccountSettingsNotificationsIT.java
src/test/java/com/mattermost/selenium/tests/AccountSettingsUsernameIT.java

Maintenance including updates for intentional change to default mention words in [MM-7881](https://mattermost.atlassian.net/browse/MM-7881).

Maintenance v5.24

---

src/test/html/ide-only/Permissions/PermissionSchemes-ComboScenarios.html
src/test/html/ide-only/Permissions/Permissions-Full.html
src/test/html/ide-only/Plugins/pluginsSettings.html
src/test/html/ide-only/_SeleniumIdeSetup/userextension-rollup.js

- Extensive changes to rollup to accommodate some user management CSS changes and changes around the post menu options
- Typical maintenance on tests themselves

5.24 Se Maintenance

---

setup-for-run.sh
src/test/html/ide-only/Auth/auth06-LDAPGroups.html
src/test/html/ide-only/Smoke/ST.html

... Plus a couple minor updates to the smoke test and an LDAP test.

Putting server on v5.27 release

---

src/test/html/ide-only/Auth/auth05-LDAPSettings.html
src/test/html/ide-only/Auth/auth06-LDAPGroups.html
src/test/html/ide-only/Auth/auth06.5-LDAPGroupSync.html
src/test/html/ide-only/Messaging/MessagingBasics.html
src/test/html/ide-only/Notifications/NotifyMan.html
src/test/html/ide-only/Notifications/NotifyMentions.html
src/test/html/ide-only/SystemConsole/sc06-EnvWebserver.html
src/test/html/ide-only/SystemConsole/sc06.5-EnvSubpath.html
src/test/html/ide-only/SystemConsole/sc07-EnvSettings.html
src/test/html/ide-only/SystemConsole/sc10-Localization.html
src/test/html/ide-only/SystemConsole/sc11-UsersTeamsMaxes.html

Some more updates from v5.28 test maintenance.

Updates from v5.28 testing
